---
title: "Group Project 2"
author: "Ana, Ellen, Rylan"
date: "2023-11-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(rpart)        # for building trees
library(rpart.plot)   # for plotting trees
library(randomForest) # for bagging & forests
library(infer)        # for resampling

library(fivethirtyeight)       # for resampling
```
## Creating the dataset

```{r}
#Read in the dataset
soccer <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-04-04/soccer21-22.csv') %>% 
rename(final_home_goals = FTHG, 
         final_away_goals = FTAG,
         full_result = FTR,
         half_home_goals = HTHG,
         half_away_goals = HTAG,
         half_result = HTR,
         home_shots = HS,
         away_shots = AS,
         home_shots_on_target = HST,
         away_shots_on_target = AST,
         home_fouls = HF,
         away_fouls = AF,
         home_corners = HC,
         away_corners = AC,
         home_yellows = HY,
         away_yellows = AY,
         home_reds = HR,
         away_reds = AR) %>% 
mutate(full_result_1 = as.factor(full_result)) %>% #Get final result as factor to be able to predict it with the forest
select(-Date, -HomeTeam, -AwayTeam, -Referee, -full_result, -final_home_goals, -final_away_goals) #Get rid of predictors that we don't want the forest to focus on
```
## Building an example tree

```{r fig.height = 8, fig.width = 8}
# STEP 1: tree specification
tree_spec <- decision_tree() %>%
  set_mode("classification") %>% 
  set_engine(engine = "rpart") %>% 
  set_args(cost_complexity = 0, min_n = 2, tree_depth = 5)
# STEP 2: Build the tree! No tuning (hence no workflows) necessary.
original_tree <- tree_spec %>% 
  fit(full_result_1 ~ ., data = soccer)

#Sample tree for us to visualize the data
original_tree %>%
  extract_fit_engine() %>%
  plot(margin = 0)
original_tree %>%
  extract_fit_engine() %>%
  text(cex = 0.8)
```
## Building the forest

```{r}
set.seed(253)

# STEP 1: Model Specification
rf_spec <- rand_forest()  %>%
  set_mode("classification") %>%
  set_engine(engine = "ranger") %>%
  set_args(
    mtry = NULL,
    trees = 500,
    min_n = 2,
    probability = FALSE,    # Report classifications, not probability calculations
    importance = "impurity" # Use Gini index to measure variable importance
  )
# STEP 2: Build the forest

# Create our forest of unpruned trees
soccer_forest <- rf_spec %>%
  fit(full_result_1 ~ ., data = soccer)
soccer_forest
```


## Making a confusion matrix

```{r eval = FALSE}
# OOB confusion matrix
oob_predictions <- soccer_forest %>% 
  extract_fit_engine() %>% 
  pluck("confusion.matrix")

oob_predictions
```
## Total counts, Accuracy per category

```{r}
A <- 90+22+17
H <- 13+13+137
D <- 33+17+38

A_acc <- 90/A
H_acc <- 137/H
D_acc <- 17/D

cat("Home team total games lost:", A, "\n")
cat("Home team loss prediction accuracy:", A_acc, "\n")

cat("Home team total games tied:", D, "\n")
cat("Home team tie prediction accuracy:", D_acc, "\n")

cat("Home team total games won:", H, "\n")
cat("Home team win prediction accuracy:", H_acc, "\n")
```
### We tend to have higher prediction accuracy for wins because our dataset is unbalanced and we have a larger number of home team wins recorded in our dataset.

```{r shiny}
#Load in shiny libraries
library(shiny)
library(vip)

#Select random game (row) from dataset
random_number <- sample(1:380, 1, replace = T)
random_game <- soccer[random_number,]

#Put model predictions in a new data frame
oob_predictions <- data.frame(soccer_forest %>% 
                                extract_fit_engine() %>% 
                                pluck("predictions"))

model_prediction <- oob_predictions[random_number, ]

#Variable importance graph
importance_plot <- soccer_forest %>% 
  vip(geom = "point", num_features = 15) +
  labs(title = "Variable Importance in the Forest")


# Define UI for application that draws a histogram
ui <- fluidPage(
  
  #Instructions
  h3("This shiny app aims to test the user's ability to predict the winning soccer team based on certain factors. 
     The user will also be able to compete against the model we created to predict the same games."),

  sidebarLayout(
    sidebarPanel(

    #Side panel with random game statistics  
      
    h1("Statistics"),

    h2("Home Team"),
    
    p("Halftime goals: ", random_game$half_home_goals),
    p("Shots: ", random_game$home_shots),
    p("Shots on target: ", random_game$home_shots_on_target),
    p("Fouls: ", random_game$home_fouls),
    p("Corners: ", random_game$home_corners),
    p("Yellow Cards: ", random_game$home_yellows),
    p("Red Cards: ", random_game$home_reds),

    h2("Away Team"),

    p("Halftime goals: ", random_game$half_away_goals),
    p("Shots: ", random_game$away_shots),
    p("Shots on target: ", random_game$away_shots_on_target),
    p("Fouls: ", random_game$away_fouls),
    p("Corners: ", random_game$away_corners),
    p("Yellow Cards: ", random_game$away_yellows),
    p("Red Cards: ", random_game$away_reds),
    
),
mainPanel(
  
  h2("To begin, select one of the buttons below."),
  
  titlePanel("Who do you think won this soccer game?"),

  
  #Buttons for user to interact with
  
  actionButton("homeAction", label = "Home team"),
  hr(),

  actionButton("awayAction", label = "Away team"),
  hr(),

  actionButton("drawAction", label = "It was a draw"),
  hr(),

  #Text output for random game, user's choice, and forest prediction
  h1(textOutput("ChoiceButton")),
  h1(textOutput("ActualResult1")),
  h1(textOutput("ActualResult2")),
  h1(textOutput("ModelResult1")),
  h1(textOutput("ModelResult2")),
  
  #Output variable importance plot
  h3("HINT: The below variables are what the model found to be most predictive"),
  plotOutput("plot"),

)
)
)


server <- function(input, output) {
  
  #Output variable importance plot
  output$plot <- renderPlot({
    importance_plot
  })
  
  #Actions if user chooses the home team
  observeEvent(input$homeAction,
               {
                 output$ChoiceButton <- renderText({
                   "You chose the home team to win"
                 })
                 output$ActualResult1 <- renderText({
                   print("The actual result was: ")
                 })
                 output$ActualResult2 <- renderPrint({
                   as.character(random_game$full_result_1)
                 })
                 output$ModelResult1 <- renderText({
                   print("The model predicted: ")
                 })
                 output$ModelResult2 <- renderPrint({
                   as.character(model_prediction)
                 })
               }
  )

  #Actions if user chooses the away team
  observeEvent(input$awayAction,
               {
                 output$ChoiceButton <- renderText({
                   print("You chose the away team to win")
                 })
                 output$ActualResult1 <- renderText({
                   print("The actual result was: ")
                 })
                 output$ActualResult2 <- renderPrint({
                   as.character(random_game$full_result_1)
                 })
                 output$ModelResult1 <- renderText({
                   print("The model predicted: ")
                 })
                 output$ModelResult2 <- renderPrint({
                   as.character(model_prediction)
                 })
               }
  )

  #Actions if user chooses a draw
  observeEvent(input$drawAction,
               {
                 output$ChoiceButton <- renderText({
                   print("You chose the teams to draw")
                 })
                 output$ActualResult1 <- renderText({
                   print("The actual result was: ")
                 })
                 output$ActualResult2 <- renderPrint({
                   as.character(random_game$full_result_1)
                 })
                 output$ModelResult1 <- renderText({
                   print("The model predicted: ")
                 })
                 output$ModelResult2 <- renderPrint({
                   as.character(model_prediction)
                 })
               }
  )
  
  
}


# Run the application
shinyApp(ui = ui, server = server)
```

